@ECHO OFF

ECHO Standard prefixed
NASM -iSRC\INCLUDE\ SRC\BOOT.ASM -o OUTPUT\BOOT.PRT
NASM -iSRC\INCLUDE\ SRC\VDIR.ASM -o OUTPUT\VDIR.PRT
NASM -iSRC\INCLUDE\ SRC\ROOT.ASM -o OUTPUT\ROOT.PRT

ECHO DIRS
NASM -iSRC\INCLUDE\ SRC\BINDIR.ASM -o OUTPUT\BINDIR.PRT
NASM -iSRC\INCLUDE\ SRC\MODDIR.ASM -o OUTPUT\MODDIR.PRT

ECHO CORE
NASM -iSRC\INCLUDE\ SRC\ROOT\COREFILE.ASM -o OUTPUT\COREFILE.PRT
NASM -iSRC\INCLUDE\ SRC\ROOT\CORESTG2.ASM -o OUTPUT\CORESTG2.PRT


ECHO Connect em all
cd OUTPUT
copy BOOT.PRT /B + VDIR.PRT /B + ROOT.PRT /B + BINDIR.PRT /B + MODDIR.PRT /B + COREFILE.PRT /B + CORESTG2.PRT /B QOS.IMG /B
cd ..
